from typing import Protocol
from my_career.domain.models import FullResume, CoverLetter


class ResumeExporter(Protocol):
    def export(self, resume: FullResume, output_path: str) -> None: ...
    def export_to_bytes(self, resume: FullResume) -> bytes: ...

class CoverLetterExporter(Protocol):
    def export(self, letter: CoverLetter, output_path: str) -> None: ...
    def export_to_bytes(self, letter: CoverLetter) -> bytes: ...
