from typing import Protocol

from my_career.domain.models import FullResume


class ResumeBoundary(Protocol):
    def get_resume(self) -> FullResume: ...
    def get_filtered_resume(self, role: str) -> FullResume: ...
    def get_available_roles(self) -> list[str]: ...
    def get_filters_for_role(self, role: str) -> list[str]: ...
